### ISSUE TITLE
Fork meeting tracker bot and adapt for our needs

### ISSUE THREAD

**Issue by kristoferlund** [CommonsBuild/coordination#1000]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Fork the Blueridger bot and adapt to fit out needs - https://github.com/blueridger/MeetingAttendanceDiscordBot

## How will it work?
This is the initial idea, exact functionality to be decided / discovered.
- Use a separate Discord channel (meeting tracker channel) for tracking meeting attendance
- Meeting facilitator activates bot before start of meeting and tells it which voice channel to monitor
- Bot checks channel at an interval throughout the meeting and keeps track of who is attending
- After meeting, bot posts a message in the meeting tracker channel, tagging all participants.
- Bot rule: A configurable threshold percentage, only participants who attended more than X% of the meeting time will be tagged in the attendance message.

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
- [ ] Add channel in Discord
- [ ] Move repository to CommonsBuild
- [ ] Choose hosting environment (Digital Ocean Apps)
- [ ] Set up CI/CD flow
- [ ] Finish bot
- [ ] Activate and install bot
- [ ] Configure SourceCred to pick up the information

## Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
For the SourceCred integration:
- @mateodaza 
- @AL0YSI0US

## 👀  Who should be in the loop about this issue?
@

**Comment by AL0YSI0US** [comment]
This bot out of the package will not track someone if they have been in attendance for less than 5 minutes, most of our meetings are in the ballpark of an hour. It should have a place to configure the time % to desired outcome.

**Comment by tamarandom** [comment]
Hey @Vyvy-vi is this an issue we should pull into this Sprint!?

**Comment by Vyvy-vi** [comment]
I think we can

**Comment by divine-comedian** [comment]
is this actively being worked on or is it icebox? @Vyvy-vi

**Comment by kristoferlund** [comment]
@divine-comedian see my comment regarding the Twitter bot.

**Comment by divine-comedian** [comment]
okay, icebox!
