### ISSUE TITLE
Twitter tracker bot

### ISSUE THREAD

**Issue by kristoferlund** [CommonsBuild/coordination#1047]
## 👇🏽  What is this issue about? Give as much detail as you can. 

The alternative to integrating with Orbit for tracking social activity is building a simple Twitter bot ourselves. 

See also: #1001

## How will it work?

- Create a separate Discord channel used as a Twitter feed. The channel would serve the dual purpose of tracking Twitter activity for SourceCred as well as being a source of information for the community - what is happening in the TEC Twitter-verse?
- The Twitter bot monitors Twitter continuously for **mentions, replies and retweets** and posts these in the Twitter Discord Channel.
- The bot reacts to every posted messages in Discord. Those reactions are used by SourceCred to calculate cred/grain.
- **Configurable option:** Different reactions for mentions, replies and retweets allows us to value those differently in SourceCred. Starting config, most likely we will value all interactions the same.
- **Question:** Would we also like to allow for community reactions being part of the cred calculation?

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
- [ ] Setup repository under CommonsBuild
- [ ] Develop and test bot
- [ ] Setup CI/CD flow
- [ ] Deploy bot to Digital Ocean App Platform (or other provider)
- [ ] Configure Discord channel
- [ ] Configure SourceCred to pick up the right information

##  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
For the SourceCred integration:
@mateodaza
@AL0YSI0US

## 👀  Who should be in the loop about this issue?
@

**Comment by liviade1** [comment]
hi @Vyvy-vi - how is the progress in this issue? is it something that should be in this sprint?

**Comment by Vyvy-vi** [comment]
If I remember correctly, Tam and I set up TweetShift in the server few months ago

**Comment by Vyvy-vi** [comment]
That bot tracks the twitter feed.
Writing data to sourcecred might require some work. (Tweaking pollen-bot to do Twitter Authentication, and write the twitter identity to sourcecred)

**Comment by liviade1** [comment]
thanks for the updates! @Vyvy-vi 
I'm talking to Kristofer he will coordinate with you on this

**Comment by divine-comedian** [comment]
@Vyvy-vi @kristoferlund do you have updates on this?

**Comment by kristoferlund** [comment]
Building a bot for sourcecred no longer feels like an option. Praise might support external bots like this but does not do so yet. Adding a feature like this is a larger change we will not attempt without having a solid lead developer onboard.
