### ISSUE TITLE
Implement Ostrom's principles

### ISSUE THREAD

**Issue by liviade1** [CommonsBuild/coordination#18]
## 🎉   Subtasks

- [ ] principle 1 and 2 - propose a written agreement of our boundaries and rules
- [ ]  principle 3 - experiment the advice process in the forum as part of submitting a proposal
- [ ]  principle 4 - it will come out of the legal working group
- [ ] principles 5,6,7 - proposal coming out of the conflict management working group
- [ ] principle 8 - proposal for our fractal configuration

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Hey @liviade1 - would you mind dropping an update in here.
