### ISSUE TITLE
Governing the Commons Bookclub 

### ISSUE THREAD

**Issue by liviade1** [CommonsBuild/coordination#189]
## 🎉 Subtasks

- [ ] host weekly calls
- [ ] send PAN to the winner 
- [ ] assign a person for facilitating the next session
- [ ] promote it 

## 🤼‍ Reviewer

@
