### ISSUE TITLE
Offboarding process for working gorups

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/coordination#194]
## 📋 Anything to add?

What happens in those sad situations that people are hurting a working group, how do we nudge them in the direction of helping the working group... and then, to go further what happens if the nudging isn't working and they keep dropping the ball? How do we off board people in a clean way.

## ⏰ Urgency/Due Date/Blockers?

Should be added to all the WGs 

## ❓ Why is it important?

Agreements need to be made, as we grow, people will 

## 🎉 Subtasks

- [x] Create the off-boarding strategy for the Community Stewards 
- [ ] Create the off-boarding strategy for the Gravity Working Group
- [x] Make an issue for finishing the task ensuring each other WG has an off boarding process

## 🤼‍ Reviewer

@liviade1 

## 🔗 Work doc - inspirational links
Stewards notes
https://docs.google.com/document/d/1VQNgAThqMLaQrF21uoQabWelnyJKLtX-TbqOl8kVb0Q/edit#heading=h.7rqvvxhzgojp

**Comment by tamarandom** [comment]
Hey @JuankBell - @liviade1 and I have penned the 

Community Stewards WG manifesto

**Comment by JuankBell** [comment]
Make a forum post to explain the step by step offboarding process & include an offboarding possibility in the Gravity Typeform https://the-commons-stack.typeform.com/to/rCVsK5RK

**Comment by JuankBell** [comment]
Great step by step process in this page (we could take some ideas to propose our own method) -> [https://usefyi.com/offboarding/]

Forum post pending, requesting Gravity support to an offboarding process (from working groups) is now an option in the Gravity Typeform. :D

![Captura de Pantalla 2021-03-22 a la(s) 7.33.36 p. m..png](https://images.zenhubusercontent.com/5fb57c9c5472cf79e80e7f7e/6495e371-5dea-482a-ba87-6d538baf81ec)

**Comment by JuankBell** [comment]
Present this offboarding process for advice before posting on forum -> https://docs.google.com/document/d/1Hs1qJ-vn5Cbb8WINV1kpVz7okBvo4VJ87Dhz0XsQ8RI/edit?usp=sharing

**Comment by tamarandom** [comment]
Hey @JuankBell I think it is well thought out and well written. I left my feedback in the doc! 🙏🏼

**Comment by JuankBell** [comment]
Feedback incorporated and posted in the forum!
Easy offboarding & rotation process for the TEC!
https://forum.tecommons.org/t/easy-offboarding-process-rotation/300
