### ISSUE TITLE
Support TEC Transparency WG

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#202]
## 🎉 Subtasks

- [ ] Check that praises are dished for all the calls
- [x] Prepare the spreadsheet for call recorders
- [x] Learn the art of recording
- [ ] Update Youtube playlists and database
- [x] Work on the Manifesto
- [ ] Weekly calls

## 🤼‍ Reviewer

@

## 🔗 Work doc - inspirational links

https://docs.google.com/document/d/1jbuqlIXd3s9gRwXbT9ND0zUbE0MaEP9EyO6sHY46iOY/edit
