### ISSUE TITLE
Post/Article on the (Polycentric) Governance in the TEC

### ISSUE THREAD

**Issue by jessicazartler** [CommonsBuild/coordination#292]
## 🎉 Subtasks

- [x] Jess write draft with JJ scaffold
- [x] Livia/Jeff/Griff review
- [ ] Jess publish & distribute

## 🤼‍ Reviewer

@Jeff-Emmett @liviade1 @GriffGreen @tamarandom 

## 🔗 Work doc - inspirational links
https://docs.google.com/document/d/1yfAbB7-lKDjXXciGuHUr1vbPsTikhdMAxNFg8g1Ihac/edit
https://miro.com/app/board/o9J_krl8Cv0=/

**Comment by jessicazartler** [comment]
<img width="478" alt="Content Diagram" src="https://user-images.githubusercontent.com/43972522/103814137-3488d600-502f-11eb-9f70-17dd2c8df619.png">

**Comment by jessicazartler** [comment]
This piece was scaffolded and in progress - Griff had suggested wait for Celeste..

I will continue working on it once I have deep dived into Celeste now that it is further along (notes/Forum post/maybe record a Q&A sesh with @Griff to produce content while learning)

**Comment by jessicazartler** [comment]
Deep diving into Celeste.. will ask @GriffGreen if I need support and will ask for his review when I get into the next phase of writing next week/sprint

**Comment by markoprljic** [comment]
@jessicazartler confirmed on TG that she's taking this into the sprint.

**Comment by jessicazartler** [comment]
Finished the draft!!! https://docs.google.com/document/d/1yfAbB7-lKDjXXciGuHUr1vbPsTikhdMAxNFg8g1Ihac/edit
Requested reviews

**Comment by tamarandom** [comment]
Update : In review process

**Comment by markoprljic** [comment]
@jessicazartler Can we finalize this in the coming sprint?

**Comment by markoprljic** [comment]
@liviade1 @GriffGreen What's the status of reviewing this?

**Comment by jessicazartler** [comment]
It's been reviewed.. it's on me for next phase - integrating the feedback.. thank you :D

**Comment by tamarandom** [comment]
Closing, it's being tracked in the Commons Stack repo now.
