### ISSUE TITLE
TEC Praise Quantification (every 2 weeks)

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/coordination#347]
## 📋 Anything to add?
Do a quantification of praise every 2 weeks

## ⏰ Urgency/Due Date/Blockers?

When : Every two weeks on a Friday or Saturday

Upcoming : 
Fri Jan 29 / Sat Jan 30
Fri Feb 12 / Sat Feb 13

## 🎉 Subtasks

- [x] Get Griff's availability and schedule it
- [x] Get 2 or 3 volunteers from the TEC Community Stewards Telegram channel (or discord when that’s live)
- [x] Put the praise quant session in the calendar and send the cal invite to the volunteers

## 🤼‍ Reviewer

@

**Comment by iviangita** [comment]
Closing for this sprint, will reopen next sprint

**Comment by tamarandom** [comment]
The bi-weekly praise quant is over. Closing!
