### ISSUE TITLE
Praise system : SourceCred

### ISSUE THREAD

**Issue by liviade1** [CommonsBuild/coordination#37]
## 🎉   Subtasks

(please refine below to reflect scope of SC)

- [x] Identify what is needed to implement source cred for the TEC 
- [x] SourceCred instance is running 
- [x] book a work session to define the parameters
- [ ] Decide how and how much we are rewarding from praise and from SourceCred so there is no double rewards.  
- [ ] sanctions for abuse of the system  
- [ ] draft a social contract/conditions notice for everyone who joins.
- [ ] Have a minimum viable solution to experiment for a few weeks before launching.

- [ ] Have working session

## 🤼‍♂️   Reviewer

@Santigs 

## 🔗   Work doc - inspirational links
https://docs.google.com/document/d/16fZG4QJycKDTGrJAKWT-caflBE3g53o1L2k64ztIlZM/edit?userstoinvite=liviaieaou%40gmail.com&ts=5f9a0367&actionButton=1

**Comment by Santigs** [comment]
Contacted with s-ben from Sourcecred. He suggested to join one of their community meetings on Tuesdays 11 am PST.

**Comment by liviade1** [comment]
Santi will join community call today

**Comment by liviade1** [comment]
Mateo is speaking with Kay

**Comment by Santigs** [comment]
Joined SourceCred community call, they are willing to better know TE Commons project and will meet again with them on Friday. I will be joined with Mateo.

**Comment by elihanover** [comment]
I am very excited by this.  You can imagine it working very elegantly with the reserve pool + conviction voting, where SourceCred acts as an accounting of who did who, and the voters can vote weekly or monthly to distribute some amount of funds to the community with more confidence it will be distributed well.

**Comment by Santigs** [comment]
Here's a video describing how the tool works
https://www.youtube.com/watch?v=38OlnEPpzeo

**Comment by Santigs** [comment]
Here's the minutes from the meeting we had with SourceCred team.
https://roamresearch.com/#/app/SourceCred/page/F2TN61FYN

**Comment by durgadasji** [comment]
I'd like to suggest we add a feature for people who come out of meetings to be notified to dish praise at that time, so those contributors don't have that stacking up over long periods and the praise can better reflect the actual content of the meeting.

**Comment by drllau** [comment]
Mathematically I think of it as a vector of measurable attributes ... one mental analogy is to think of a rainforest with compost/litter being the commons (social channels), grass as response/likes, underlayer as substantive contributions to docs/working groups, canopy as active participation in proposals and emergent as high level advances in the art of token engineering. You then have some sorta eigenvalue normalisation function so that you map rough equivalence or scaling so that regular systematic participation might equate to one-off coding review of a proposal (in terms of TEC issued). 

![canopy](https://user-images.githubusercontent.com/14944510/101447914-23ca3f00-3961-11eb-8a7c-95a6eaa9fa93.png)

**Comment by tamarandom** [comment]
@Santigs Testing notifications, please ignore ;)

**Comment by Santigs** [comment]
This is the process we are following.


![SourceCred.png](https://images.zenhubusercontent.com/5fb4c5aafa96a83dd2ee0a6c/3ca5a9d9-8a70-4cc7-934a-f6e2b4946e1c)

**Comment by jessicazartler** [comment]
😮 awesome.

**Comment by Santigs** [comment]
After talking with the users responsible for SourceCred in the 1Hive community, they suggested not to touch the parameters of the edges from the graph, only play with the Nodes. Touching any edge affects the whole graph. 
They suggested only set to zero the emoticons if we are not using them.

I also had a meeting with Santiago to define the dashboard we will have to show the information to the community in a graphical format. Adding more info than the one we get to see now from the standard panel. 

We should have some initial visualizations by next week
