### ISSUE TITLE
Weekly Scheduling of Tweets

### ISSUE THREAD

**Issue by jessicazartler** [CommonsBuild/coordination#382]
## 📋 Anything to add?

I should have been having issues for this every week! Promoting calls/events, RTing, sharing articles

## ❓ Why is it important?

External Comms about events/happenings/calls

## 🎉 Subtasks

**WEEKLY COMMUNITY CALLS ON THURSDAYS**
- [ ] Change the dates on the graphic
- [ ] Schedule one Tweet the day before using the call graphic and content template, or feel free to change it up a bit
- [ ] Schedule one Tweet one hour before using the group call photo and content template, or feel free to change it up a bit  

**WEEKLY TEC LABS (Event Organizer: Shawn)**
- [ ] Change the date/title on the graphic
- [ ] Schedule a Tweet the day before using the graphic and content template but changing the content to whatever the topic of the week is
- [ ]  Schedule a Tweet one hour before using the graphic and content template but changing the content to whatever the topic of the week is, feel free to change it up a little

**GRAVITON TRAINING (Event Organizer: Juan)**
- [ ] Get the graphic of the week from Juan, make sure date/time is correct
- [ ] Schedule a Tweet the day before using the graphic and content template but changing the content to whatever the topic of the week is
- [ ] Schedule a Tweet one hour before using the graphic and content template but changing the content to whatever the topic of the week is, feel free to change it up a little

**TEC AMA (Event Organizer: Eduardo/Livia)**
- [ ] Change the dates on the graphic
- [ ] Schedule one Tweet the day before using the call graphic and content template, or feel free to change it up a bit
- [ ] Schedule one Tweet one hour before using the graphic and content template, or feel free to change it up a bit  

**BI-WEEKLY PRAISE QUANT/NEWS BLOG**
- [ ] Tweet once published -- use template but change for the new news blog

**GUEST BLOGS** - if we get a submission, TBA

**OTHER RTs** - May share links with you for Retweeting, also, if you see any @mentions that are appropriate, feel free to ask anytime you have questions 

**<3 HEARTING** - Heart any mentions of @tecmns 

*For questions about events, ask event organizer - for questions about content edits, ask Jess

## 🤼‍ Reviewer

@markoprljic @tamarandom 

## 🔗 Work doc - inspirational links

GRAPHICS TEMPLATES HERE (feel free to ask if you need help)
https://docs.google.com/presentation/d/1zcisOx79Ia5bCwzxQALYR29J4DN-_0ndIBJHo0yE5Dg/edit#slide=id.gae877f9d60_0_93

**Comment by jessicazartler** [comment]
Setting up a 30min call w/ Ivy today/tomorrow to go over this and hand off
https://github.com/TECommons/coordination/issues/383

**Comment by jessicazartler** [comment]
Ivy made this doc from this issue/this morning's session:
https://docs.google.com/document/d/1Sf9p05e8rjeUZaFFrjoRPmUOdTJcb8sk7xhK3UC8rNw/edit?usp=sharing

Awesome @iviangita !

**Comment by iviangita** [comment]
Added TEC AMA in the recurring content

**Comment by jessicazartler** [comment]
Awesome! Thanks @iviangita !!

**Comment by iviangita** [comment]
We'll start sharing the community call video on Twitter too! Here's the edited content from Comms - see [issue 19](https://app.zenhub.com/workspaces/tec-content-production-and-distribution-60549332d7d741001bbea827/issues/commonsbuild/content-distribution/19):

Not able to join our Community Call yesterday? No problem, it’s on our YouTube channel. From the Praise Fest to our Working Group updates to the TE Project Spotlight at the end, they are always high vibe, good times! raised_handsspeaking_headstar2
Watch now: (link)

**Comment by tamarandom** [comment]
@chuygarcia92 - I'll make you the owner for now, ok? Or we can put on @Razga straight away? What do you think?
