### ISSUE TITLE
Decide if we should create a Community Management Working Group?

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/coordination#442]
## 🎉 Subtasks

- [ ] First we decide
- [ ] Find an Owner for the process

----------- proposed process---------

- [ ] Advertise the need? 
- [ ] Interview Candidates?
- [ ] Choose a Candidate

## 🤼‍ Reviewer

@

**Comment by tamarandom** [comment]
Closing this one! 

We can revisit this at a later date but the high priority need is resolved by onboarding Katy as onboarding coordinator.
