### ISSUE TITLE
Tamara / Hatch Outreach (see Epic for details)

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#493]
**Sprint 6**
Sharing updates in the comments section! 

**Sprint 5**
- [x] Tannr  - mtg planned
- [x] Federico - mtg planned
- [x] Fabian - mtg planned
- [x] Amin
- [x] Wesley - mtg planned
- [x] Angela - mtg planned

**Comment by tamarandom** [comment]
The session with Stefaan will have to be next Sprint, or beyond, but was able to find a common time with all the rest for this sprint.

**Comment by tamarandom** [comment]
Here is my plate for Sprint 6. The Curate xls is the single source of truth but I will periodically drop updates here too.

![Screen Shot 2021-03-23 at 11.16.56 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/a7d9ae8e-ed6e-4a27-b29e-5c6dbe2ecca7)

**Comment by tamarandom** [comment]
This was a very active week - 8 over the last week alone. Preparing another batch to reach out to in order to setup new sessions on the calendar!

**Comment by tamarandom** [comment]
Sprint update:

Did Hatcher sessions and/or follow-ups with : Jonathan, Luuk, Daud, Rovers, Evrim, Vyvy-vi, Felipe, Ata, Mount Manu.

More in the pipeline.

**Comment by tamarandom** [comment]
Went deep on key Token Engineers and those building actively (and for many years) in the space. 

Tomer (good dollar and more), Mihai (ARK project), Julio (Circles), Jantine (Tezos), Dani (Tezos), Max (leapdao), Victor (Leapdao), Max (carbonbase), Abbey (Radicle)

Most of these were recommended by @jessicazartler and that's how they got on this Hatcher list. Praise @jessicazartler 🤗

**Comment by jessicazartler** [comment]
You da best @tamarandom <3 Keep up the incredible work!

**Comment by tamarandom** [comment]
Hatcher outreach sessions have slowed this Sprint in favor of concentrating more effort on explainers and more helpful content to share. Happy with the progress. But in terms of reaching out to Hatchers, the Param parties have been amazing way to get the word out and explain more about the groundbreaking approach of the TEC!!

**Comment by tamarandom** [comment]
No formal outreach sessions this Sprint but follow-ups to those that we have already reached out to for:

Two outreach campaigns started. 
1. Vote for params (for anyone that has IH and/or CSTK)
2. IH associated with non-activated TS members will be lost forever on the day of the Hatch

Campaign outline:
https://docs.google.com/document/d/1YvzrtMnfTOEr-e5wi8nsBmmgcyyxFki5RxvMKBC4nx4/edit#heading=h.qlstezypk4i3

**Comment by tamarandom** [comment]
Done, done and done.
