### ISSUE TITLE
Discussion on Multiple-ban bot, the recent bot-attacks, and the Auth site

### ISSUE THREAD

**Issue by Vyvy-vi** [CommonsBuild/coordination#562]
## 📋 Anything to add?
This issue comes from #499 and #484 
This issue is sort of a culmination of the spam/scam bot issues, and prevention methods relating to that.

Q) Why a new issue?
Issue #499 could have been fine for this, however, the purpose of that issue, was to research on improving Onboarding Experience, but the current concern in this issue(#562) is regarding-
- Prevention of Spam/Scam Bots
- Safety issues with the newly created `TEC Automation` bot and power regulation(to be consulted on by both Gravity and Soft-gov _I think_) and finding a safe way of having a bot that can ban multiple bot users or discussing if this new bot should be removed.

## ⏰ Urgency/Due Date/Blockers?
Blockers - #499 
Urgency - The sooner, the better

## ❓ Why is it important?
No one likes scam bots. Specifically, we are onboarding new people to TEC and maybe they get one of these scam dms and think of it as something real. Moreover, it seems like these attacks are somewhat targetted(the bots named "Tesla")
#499 should potentially resolve parts of the problem, with the new 'fill-captcha-to-get-access' site. However, even after captcha a few bots can get in :/ (There are a few tools that people can use to bypass Captcha- Puppeteer automation with c)

Special consideration is needed on the additional bot added `TEC Automation`, which has multi-user ban powers.
As of now, only `Admin` role has access to it, however later on it might be better if the power is distributed through a new role, to only a few Gravitons, Stewards and Admins. This bot can be abused by people who can access it, to pretty much ban everyone*.
*The power consideration is being taken into account and perhaps it would be best if the muti-ban bot can only ban new members. Moreover, should this bot stay or not?

## 🎉 Subtasks

- [x] Discuss on possible solutions to stop these spam bots(esp. the ones named "Tesla")
- [x] Discuss on how to enforce captcha on the new bot
- [x] Discuss on whether the `multi-ban` bot should be present in the server
- [x] Discuss on possible restrictions on the `multi-ban` bot, to ensure that it isn't mis-used(like needing approval from 1 Graviton + 1 Admin + 1 Steward)
- [x] Discuss on power permissions for `multi-ban` bot (named "TEC Automation")

## 🤼‍ Reviewer

@

## Additional Context-
The new added bot(`TEC Automation`), was used to ban all the spam bots

![Multiple Spam bot- "Tesla", being banned](https://user-images.githubusercontent.com/62864373/112514405-491d7480-8dbb-11eb-9ea2-9ffffb6dc5fc.png)
![Me getting tired of manual banning](https://user-images.githubusercontent.com/62864373/112514650-8aae1f80-8dbb-11eb-8a8d-0fcffddd29a9.png)

**Comment by liviade1** [comment]
@krisjpi might have some insights here

**Comment by tamarandom** [comment]
@Vyvy-vi -- @krisjpi and Kay (@geleeroyale) should be able to help with this.

**Comment by markoprljic** [comment]
@Vyvy-vi Did you try to reach out to @krisjpi and @geleeroyale and discuss the points in the checklist of this issue? If you have had any conversations so far please let me know. Likewise, let me know if we need to set up a quick hack sesh on this.

**Comment by markoprljic** [comment]
> Discuss on whether the multi-ban bot should be present in the server
Yes.

> Discuss on possible restrictions on the multi-ban bot, to ensure that it isn't mis-used (like needing approval from 1 Graviton + 1 Admin + 1 Steward)
To prevent "mis-use", example- Someone is banning the "Tesla" bot, but there is also someone(actual human) in the server with a same name. Solution: The bot prints out a list of people who are being banned, before banning. We could maybe check if someone we know is getting banned by mistake

> Discuss on how to enforce captcha on the new bot
The discord invite can be done via the site- https://tec-discord-oauth2.vyvyvi.repl.co/
(Just need to style the page and I think that should solve most of our bot issues)

> Discuss on power permissions for multi-ban bot (named "TEC Automation")
Stewards and Admin to have powers to use the multi-ban bot.

**Comment by tamarandom** [comment]
Update : this can be closed now!
