### ISSUE TITLE
Principle 1 and 2 - propose a written agreement 

### ISSUE THREAD

**Issue by liviade1** [CommonsBuild/coordination#57]
## 📋   Anything to add?
1. Commons need to have clearly defined boundaries
2. 2. Rules need to fit local circumstances.
## 🎉   Subtasks

- [x] Have a practice to identify which rules and boundaries are naturally emerging from our culture 
- [x] forum post
- [x] second session in coordination to legal and gravity 
- [ ] write the collaborative document with all the codes of conduct 
- [ ] propose them as a collective agreement 
- [ ] have suggestions for how to keep them alive in our culture
- [ ] propose a process to revise and update them in the future

## 🤼‍♂️   Reviewer

@

**Comment by GriffGreen** [comment]
Boundary is pretty simple I think... Token holders :-D

**Comment by liviade1** [comment]
https://docs.google.com/document/d/1S5EoWbsFt3uQ5Wj6yyUJKyApFyjCQ-EloZAr6W55N3U/edit#heading=h.k0llgx5ep8nl

**Comment by liviade1** [comment]
all the agreements are now on github so this proposal will happen in the next sprint
