### ISSUE TITLE
Promote Comms call one hour before in Discord & Praise attendees

### ISSUE THREAD

**Issue by jessicazartler** [CommonsBuild/coordination#574]
## 📋 Anything to add?

Promote Comms call one hour before as a reminder on Discord and follow up right after the meeting to praise attendees

## 🎉 Subtasks

- [ ] Update graphic with date
- [ ] Post message in TEC general channel
- [ ] Praise Comms WG call attendees

## 🤼‍ Reviewer

@tamarandom 

## 🔗 Work doc - inspirational links
https://docs.google.com/presentation/d/1zcisOx79Ia5bCwzxQALYR29J4DN-_0ndIBJHo0yE5Dg/edit#slide=id.gc048f8b484_1_257

**Comment by markoprljic** [comment]
Thanks Jess, I'm also assigning @chuygarcia92 to this issue as he'll be helping us with PM in Comms.

**Comment by jessicazartler** [comment]
Awesome!! Thank you both!!! :D

**Comment by tamarandom** [comment]
Automating this should make it into the new sprint. #578

**Comment by markoprljic** [comment]
Revised template with new Discord VC link.

Hi everyone :grin::sunny::rainbow:

:telephone: Comms Working Group call in 1 hour on Working Group VC - Comms channel https://discord.gg/s2JuQCBNS4

AGENDA & CALL NOTES
https://docs.google.com/document/d/1UTNNyYLf6WC1wlytoU9IJ46z2I32NX0MrtJOs3j9Ahw/edit

MIRO BOARD
Link: https://miro.com/app/board/o9J_kjDw5AE=/
Password: TokenEngineering

MANIFESTO (Open for revision)
https://docs.google.com/document/d/17w_UVi7lJjUNtj1Ji1WGd7Osk-E0edmfIRNoGRSP3yI/edit#
