### ISSUE TITLE
Identify potential hatchers & connect with Hatcher Outreach

### ISSUE THREAD

**Issue by jessicazartler** [CommonsBuild/coordination#577]
## 📋 Anything to add?

Go through my partnerships list & friends to identify and cross-reference with Tam if they have joined the TS, onboard them to TEC hatch

## 🎉 Subtasks

- [x] ID potential hatchers, group onboardings
- [ ] Create msg template & list
- [ ] Send messages & add Tam to group chats as appropriate
- [ ] Schedule & attend when support needed outreach sessions w/ Tam

## 🤼‍ Reviewer

@tamarandom

**Comment by jessicazartler** [comment]
Sorry @tamarandom can you remind me where we are tracking hatchers? Would love to look at the list, add names/projects and talk to you about creating a msg template to send around - could we do a 15-30min kickoff call to sync on this? OR I can start the list and give you all the handles..

**Comment by tamarandom** [comment]
We synced already but for the purpose of having these docs always handy

TEC Curate list
https://docs.google.com/spreadsheets/d/1RJK8gPqUoRfehX9e60sTCMAM_R1rI2CuiV1r-i3wAXQ/edit#gid=0

TEC Hatch deck 
https://docs.google.com/presentation/d/1itLeveA9vXmaN9hXVVELZ_i4oFklr8RZpSxE1E1Vhqc/edit#slide=id.gc048f8b484_1_122

Hatch Outreach "script" (this includes that initial outreach message)
https://docs.google.com/document/d/1DcUsEQ0XpHhCsA97c0HZhX2RofOaTEzLTE-51PGlWFs/edit#

**Comment by jessicazartler** [comment]
You da, you da bestttttt

**Comment by tamarandom** [comment]
🦋 🐝

**Comment by jessicazartler** [comment]
I combed almost my WHOLE telegram haha and pulled the people who I thought were most interested/badasses that I've chatted with.. and also added some groups.. and for the 2nd - I added those who were tightest with the peoples

Have a sync with Griff today to talk about the strategy/efforts, and Tam will sync with you next week and let me know if you have any questions :D

**Comment by tamarandom** [comment]
Thanks for all of these excellent leads, @jessicazartler ! As it's part of th ongoing Hatcher Outreach (being tracked in Curate daily!) we can close this one out. As I reach out to the Hatchers I will coordinate with you on timings in the cal.

**Comment by tamarandom** [comment]
Hey Jess, there is a new issue for you for ongoing Hatch Outreach now & I'm closing this one. Great leads, can't wait to so sessions with you ... 

https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/commonsbuild/coordination/641

**Comment by jessicazartler** [comment]
Thank Tam! Me too <3

**Comment by tamarandom** [comment]
I made a new issue to track the Hatch Outreach sessions. So it's on your plate this Sprint. 
https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/commonsbuild/coordination/641
