### ISSUE TITLE
MVV final steps 

### ISSUE THREAD

**Issue by liviade1** [CommonsBuild/coordination#642]
## 🎉 Subtasks

- [ ] hack session on Sunday 
- [ ] Promote
- [ ] Share results on Tuesday 
- [ ] close issues 
- [ ] Promote the new MVV everywhere 

## 🤼‍ Reviewer

@
