### ISSUE TITLE
Discord Bot to store wallet addresses (for sourcecred)

### ISSUE THREAD

**Issue by Vyvy-vi** [CommonsBuild/coordination#666]
## 📋 Anything to add?
@liviade1 shared a feature request to add an automation to collect wallet addresses and send/transfer the data to a spreadsheet.
(*Edits might be needed here for more details^^)

## ⏰ Urgency/Due Date/Blockers?
- Due date: 1-3 days
- Blockers: 
  - [ ] Sorting out the deployment and which spreadsheet to use
  - [x] Discuss on which fields to store(map through discord name or discord id)

## ❓ Why is it important?

This might make it easier to manage the wallet addresses of people in the discord, esp. for sourcecred and the same spreadsheet could be referred to when there is a need of minting any tokens.

## 🎉 Subtasks

- [x] Decide if we need a spreadsheet or can any other medium be alright(Google's spreadsheet API is messy with concurrency)
- [x] Decide on what fields need to be stored

## 🤼‍ Reviewer

@

**Comment by liviade1** [comment]
Hey @mateodaza @Santigs would be good to hear your thoughts here

**Comment by Vyvy-vi** [comment]
There's a level of working set up here-
(Note- This isn't the final version, but since the data is on a database, this can be rendered onto a site/any other form which might be more helpful for anyone updating this with the sourcecred instance, or in case we automate the entry to sourcecred, accessing data from mongo should be straight-forward)
Link to PR: https://github.com/Vyvy-vi/TEC-Discord-Automation/pull/13

The outputted list is a `.txt` file-
![Screenshot 2021-05-02 at 10 41 17 PM](https://user-images.githubusercontent.com/62864373/116822150-c8f8e480-ab9a-11eb-89de-66bb5746c09c.png)

**Comment by Vyvy-vi** [comment]
Update: I worked on this a bit, and there are currently 2 approaches to storing the data.
Both the approaches can be used, however, we should discuss which one would be better and easier for the people filling the information.
<table>
<tr>
<td>via FORM</td>
<td>via COMMAND</td>
</tr>
<tr>
<td>
<img src="https://user-images.githubusercontent.com/62864373/119002082-2cac4b80-b9aa-11eb-9223-9b513b1e43ec.gif" alt="As a form">
</td>
<td>
<img src="https://cdn.discordapp.com/attachments/831192353812381715/844288265196142602/Screenshot_2021-05-19_at_12.29.09_AM.png" alt="As a single command">
</td>
</tr>
</table>

**Comment by Vyvy-vi** [comment]
from last call, the [COMMAND method](https://camo.githubusercontent.com/11b36dac409f82cf4196472807a00e909707e14735a4d11067b19813e6760533/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3833313139323335333831323338313731352f3834343238383236353139363134323630322f53637265656e73686f745f323032312d30352d31395f61745f31322e32392e30395f414d2e706e67) was preferred, and thus we'll use that :)

Q) What are the thoughts on what schema or format should the stored data followed?:
There's a forum discussion from praise analysis, that discusses something about this -
https://forum.tecommons.org/t/pre-hatch-impact-hours-distribution-analysis/376/25

I think there's a need for discussion over which format of storage would be great

**Comment by Vyvy-vi** [comment]
I'll probably be shifting the DB to https://airtable.com/ so that it can be easily shared with people part of the sourcecred team/DAO

**Comment by Vyvy-vi** [comment]
Q) When Mateo's has entered the data, we can flush it, right?

**Comment by liviade1** [comment]
Hey @Vyvy-vi , sorry I'm just finding this issue now, is there something still need here?

**Comment by natenatesoo** [comment]
Update: Potentially closed.

**Comment by Vyvy-vi** [comment]
The bot has this implemented, however moving forward, I think it might be of utility for us to fork the `pollen-bee` bot and related automations that 1Hive built for their sourcecred instance
