### ISSUE TITLE
 TEC Hatch visual explainer - spread far and wide 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#688]
## 📋 Anything to add?

- [x] TEC Hatch deck
- [x] Gitbook 
- [x] Post on Forum
- [x] Attribute credit to: Joe Zandstra, Tamara Helenius, Jeff Emmett
- [x] updates on : https://forum.tecommons.org/t/3-become-a-hatcher/101

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by tamarandom** [comment]
Pending the final version. There were some minor things changed and it's worth holding off distribution until those are done but it is looking .... 🔥🔥🔥

**Comment by tamarandom** [comment]
In progress

**Comment by tamarandom** [comment]
Finished that last piece to post to the forum. I'm seeing the proliferation go beyond my wildest dreams. Lookie here:

![Screen Shot 2021-07-09 at 6.13.34 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/b073edab-558a-4200-ad06-fccfa3ee9f12)
