### ISSUE TITLE
Checklist for new Working Groups 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#747]
## 👇🏽  What is this issue about? Give as much detail as you can. 
What are the little things that we need to do to add a new WG? Things like: discord channels, add to forum, update community call agenda, etc....

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. We have a checklist for what needs to be done for a new WG 
2. All the Stewards know about it ;)
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@tamarandom @liviade1 @Vyvy-vi 

## 👀  Who should be in the loop about this issue?
@stewards

**Comment by tamarandom** [comment]
@ddan4 - would this be something you would be interested in doing?

**Comment by Vyvy-vi** [comment]
I think these might be some of the things to be added -
- [ ] Discord channel
- [ ] WG Meeting schedule to TEC calendar
- [ ] Set up a welcome doc(and meeting/agenda/etc. doc)
- [ ] Adding Working Group as Topic under "Working Groups" category on the forum (https://forum.tecommons.org/c/working-groups/13) and making a post about the WG
- [ ] Choose WG emoji :P (haha this is a joke, but most WGs have one)
- [ ] Call Alert workflow(if needed)
- [ ] Add the WG title and manifesto/agendas on the gitbook in `cultural-components`
- [ ] Maybe pin some info and details about the WG in the respective discord channel, for easy onboarding
- [ ] Maybe add a relevant label to the coordination repository, so that we could use the kanban board on ZenHub for planning
- [ ] Contact Kay, if the WG needs to be bridged to some other discord or telegram group
- [ ] If it's a special WG(involving the need for some moderation powers/something of the sort), contact one of the stewards to get a new role made for the WG. (example - Instances of Wg that might be similar to Gravity, SoftGov or transparency)
- [ ] Make slides for the WG call/media so that those graphics can be shared on Twitter/telegram whenever there's a call or something

**Comment by ddan4** [comment]
sorry, just saw this. this is a good issue for me to keep an eye on, and maybe help with, because I definitely wouldn't have known all those things..  will check with vyvy-vi to see how I may be of assistance!

**Comment by Zeptimus** [comment]
"Get access to the youtube and make a playlist for that WGs call recordings" I think it depends on the steward if he wants to do it, what i would say it's make sure the recordings are availalbe via pawa or normal recording to upload. Some WGs might want take care of it but others might ask for  help, lets make sure its being done. 

 Tomorrow im onboarding heater to the recording crew since he also its building a new WG and some meetings are happening at the same time

**Comment by phacker3** [comment]
Hey all! I chatted with Zeptimus today and he pointed me here. the check-list looks great! - one question I have though is when should a new TEC Working Group be created? I personally have some intuition around this just because I've experienced how the TEC works (and asked Livia 😄), but is there a formal definition? If might help folks (including myself!) understand if they should / shouldn't try to create one.

**Comment by Zeptimus** [comment]
I think the most important document it's the manifesto and the rest goes naturally following our processes. It's super awesome, we have this checklist. I would not have all these requirements as a must but as a guide. In my personal opinion the most important thing its the manifesto and roadmap and show the community the results.

**Comment by tamarandom** [comment]
Update: @tamarandom volunteering to figure out what to do with this excellent list

**Comment by tamarandom** [comment]
CC @liviade1 

@Vyvy-vi can we talk about making this a formal doc for working groups to know how to launch themselves and then close this issue.

**Comment by tamarandom** [comment]
@natenatesoo going to help on this!

**Comment by natenatesoo** [comment]
Update: Review the checklist, and encourage more dialogue around WG formation and dissolution.

**Comment by tamarandom** [comment]
@freshelle - have you a little time to work with me or @Vyvy-vi  on this? The piece of work is just to make the info captured in here available as either a word document or in the TEC handbook (we can check with @liviade1 which one is better).

**Comment by freshelle** [comment]
@tamarandom, I drafted this [checklist ](https://docs.google.com/document/d/19CgtAf9pVzUApcduzprwE_1M2lsaNG6wvSBUHEmEKJs/edit?usp=sharing) with the big help of @iviangita

**Comment by tamarandom** [comment]
Hi Freshelle. This is great, thank you! I just had one questions and I dropped it in the doc. 
I added the doc to our gitbook TEC-Source:
https://app.gitbook.com/o/-MRe_DImEWCFDsZ_TQd2/s/-Mj5bOyMOomkgNfE--be/c/pLhuCnzAF3zXCzau8kfA/working-groups/stewards-wg

Closing!
